name: C/C++ CI

on: [push, pull_request]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
    - uses: CFD-GO/checkout@v1
    - name: make
      run: make
    - name: make check
      run: make check
  build2:
    runs-on: self-hosted
    steps:
    - uses: CFD-GO/checkout@v1
    - name: make
      run: make
    - name: make check
      run: make check
